### ISSUE TITLE
Chit chat box is not visible

### ISSUE THREAD

**Issue by Saket8** [RittmanMead/ChitChat#1]
Hi ,

Did all the steps exaclty as mentioned in the forum but still it is not reflecting.May i know if any additional changes are required? I am sure i have not missed any single step !!

**Comment by barretbse** [comment]
Hi @Saket8 ,

Which version of OBIEE are you using?

Could you please confirm that "Socialize" deployment is installed and active in WebLogic Administration Console?

**Comment by Saket8** [comment]
Hi barretbse,
Oracle Business Intelligence Product Version # 12.2.1.2.0

Yes the "Socialize" deployment is installed and is active as well as running 
Image attached.

![image](https://user-images.githubusercontent.com/40419647/41720881-0551b1a2-7582-11e8-9b0e-9a1d146f81d1.png)

**Comment by barretbse** [comment]
Hi @Saket8 ,
Could you please share the content of ChitChat database table APPLICATION_CONSTANT?
Did you update the values to reflect your installation?

**Comment by Saket8** [comment]
Hi Barretbse,

Please find below image of the table APPLICATION_CONSTANT.
Where serverport-23002 is our Managed Sever(Analytics) port and the
Rest values are updated as per our instance.

![image](https://user-images.githubusercontent.com/40419647/41758310-62dbf0ac-7605-11e8-873b-9b5940871676.png)

**Comment by barretbse** [comment]
Hi @Saket8 ,

The APPLICATION_CONSTANT table looks ok.

Which browser are you using? Is JavaScript enabled?

What do you get in the dashboard page when you try to enable the application? Could you please provide a screenshot of the code added to the dashboard?

**Comment by Saket8** [comment]
Hi barretbse,

I am using chrome however i tested same in mozilla ,ie as well and javascript is enabled in all of them.

Edit dashboard page.
![image](https://user-images.githubusercontent.com/40419647/41767173-95741852-7626-11e8-9a89-a43276a24c99.png)

Code added as below: 
![image](https://user-images.githubusercontent.com/40419647/41767210-a959ac7e-7626-11e8-96bb-a552d98d0ca2.png)

And this is what i get after save and run 

![image](https://user-images.githubusercontent.com/40419647/41767251-c27bb5d0-7626-11e8-8004-b33e7f53ad6c.png)

Please suggest !!

**Comment by barretbse** [comment]
Hi @Saket8 ,

The code to enable the application must be included only once per dashboard page and it must be added to a new column on the right-side of the dashboard page.

I would remove Section 1 (and its content) from Column 1, and drag Section 3 from Column 2 to Column 1. This should fix your issue.

**Comment by Saket8** [comment]
Hi @barretbse 

This is how it looks now.Hope i am doing it right this time .
Still it dsnt work

![image](https://user-images.githubusercontent.com/40419647/41770344-839a6e66-762f-11e8-9157-ed35ada3a50b.png)

**Comment by Saket8** [comment]
Hi @barretbse 

Just to update you, i tried the same thing in our other instance and it worked.
Must have some internal  issue with our previous instance.

Thanks !!
